Repository AlPomo/AlgorithmReview, pull requests merged in 2020-12, with the labels that each got.

#2 [+] boj 11052 Yoonsik Python
  Baekjoon/Week01/11052_Y.py
Labels: 다이나믹프로그래밍

#3 [+] boj 11052
  Baekjoon/Week01/11052_G.py
Labels: 구현, 다이나믹프로그래밍

#1 [+] boj 1213 java
  Baekjoon/Week02/1213_H.java
Labels: 구현, 다이나믹프로그래밍

#4 [+] boj 2146 백준_2146_파이썬_김윤식
  Baekjoon/Week02/2146_Y.py
  Baekjoon/Week02/2504_Y.py
Labels: 너비우선탐색

#5 [+] boj 2146 haeun java
  Baekjoon/Week02/2146_H.java
Labels: 너비우선탐색

#8 [+]boj 15658 백준_파이썬_김윤식
  Baekjoon/Week02/15658_Y
Labels: 깊이우선탐색, 백트래킹

#10 [+] boj 15658 연산자 끼워넣기 (2) java
  Baekjoon/Week02/15658_H.java
Labels: 구현, 깊이우선탐색, 백트래킹

#12 [+] boj 2504 괄호의 값 java
  Baekjoon/Week02/2504_H.java
Labels: 구현, 스택, 자료구조, 재귀

#20 [+]boj 2346 풍선 터뜨리기_파이썬_김윤식
  Baekjoon/Week03/2346_Y.py
Labels: 재귀

#24 [+] boj 1158 요세푸스 Python
  Baekjoon/Week03/1158_G.py
Labels: 자료구조

#23 [+] boj 2346 풍선터뜨리기 Python
  Baekjoon/Week03/2346_G.py
Labels: 자료구조

#31 [+] boj 1158 요세푸스 문제 java
  Baekjoon/Week03/1158_H.java
Labels: 자료구조

#27 [+]boj 1158 요세푸스_파이썬_김윤식
  Baekjoon/Week03/1158_Y.py
Labels: 구현

#30 [+] boj 2776 암기왕 Python
  Baekjoon/Week03/2776_G.py
Labels: 구현, 정렬

#17 [+] boj 2346 풍선 터뜨리기 java
  Baekjoon/Week03/2346_H.java
Labels: 자료구조

#32 [+] boj 2776 암기왕 java
  Baekjoon/Week03/2776_H.java
Labels: 이분탐색, 자료구조, 정렬, 해시를 사용한 집합과 맵

#36 [+]boj 2776 암기왕_파이썬_김윤식
  Baekjoon/Week03/2776_Y.py
Labels: 구현, 투포인터, 해시를 사용한 집합과 맵

#33 [+] boj 14891 톱니바퀴 java
  Baekjoon/Week03/14891_H.java
Labels: 구현, 시뮬레이션

#37 [+]boj 14891 톱니바퀴_파이썬_김윤식
  Baekjoon/Week03/14891_Y.py
Labels: 구현, 시뮬레이션

#40 [+] boj 14891 톱니바퀴 Python
  Baekjoon/Week03/14891_G.py
Labels: 시뮬레이션, 자료구조, 재귀

#49 [+]boj 1654 랜선자르기_파이썬_김윤식
  Baekjoon/Week04/1654_Y
Labels: 이분탐색

#48 [+] boj 2559 수열 java
  Baekjoon/Week04/2559_H.java
Labels: 누적합, 투포인터

#52 [+]boj 2493 탑_파이썬_김윤식
  Baekjoon/Week04/2493_Y.py
Labels: 스택

#50 [+]boj 2559 수열_파이썬_김윤식
  Baekjoon/Week04/2559_Y
Labels: 투포인터

#56 [+] boj 2493 탑 java
  Baekjoon/Week04/2493_H.java
Labels: 스택, 자료구조

#55 [+] boj 12865 평범한 배낭 java
  Baekjoon/Week04/12865_H.java
Labels: 다이나믹프로그래밍, 메모이제이션

#54 [+] boj 2493 탑 Python 노건훈
  Baekjoon/Week04/2493_G.py
Labels: 스택, 자료구조

#53 [+] boj 12865 평범한 배낭 Python 노건훈
  Baekjoon/Week04/12865_G.py
Labels: 다이나믹프로그래밍

#51 [+]boj 12865 평범한배낭_파이썬_김윤식
  Baekjoon/Week04/12865_Y.py
Labels: 다이나믹프로그래밍, 재귀

#47 [+] boj 1654 랜선 자르기 java
  Baekjoon/Week04/1654_H.java
Labels: 이분탐색

#45 [+] boj 1654 랜선자르기 Python 노건훈
  Baekjoon/Week04/1654_G.py
Labels: 이분탐색
