Repository AlPomo/AlgorithmReview, pull requests merged in 2021-01, with the labels that each got.

#58 [+] boj 15815 천재수학자 성필 Python 노건훈
  Baekjoon/Week05/15815_G.py
Labels: 스택, 자료구조

#59 [+] boj 5904 Moo게임 Python 노건훈
  Baekjoon/Week05/5904_G.py
Labels: 구현

#60 [+] boj 1918 후위표기식 Python 노건훈
  Baekjoon/Week05/1918_G.py
Labels: 스택, 자료구조

#61 [+] boj 5904 Moo게임 java
  Baekjoon/Week05/5904_H.java
Labels: 다이나믹프로그래밍, 분할정복, 재귀

#62 [+] boj 15815 천재 수학자 성필 java
  Baekjoon/Week05/15815_H.java
Labels: 스택, 자료구조

#63 [+] boj 4781 사탕가게 java
  Baekjoon/Week05/4781_H.java
Labels: 다이나믹프로그래밍

#64 [+] boj 1918 후위 표기식 java
  Baekjoon/Week05/1918_H.java
Labels: 스택

#65 [+]boj 15815 좋은 수학자 성필_ 파이썬_김윤식
  Baekjoon/Week05/15815.py
Labels: 스택

#67 [+]boj 1918_후위 표현식_파이썬_김윤식
  Baekjoon/Week05/1918.py
Labels: 스택

#66 [+]boj 5904_Moo게임_김윤식
  Baekjoon/Week05/5904.py
Labels: 분할정복, 재귀

#74 [+]boj 택배_김윤식_파이썬
  Baekjoon/Week07/1719_Y.py
Labels: 다익스트라

#73 [+]boj NQueen_파이썬_김윤식
  Baekjoon/Week06/9963_Y.py
Labels: 백트래킹
